grace_dir: data/raw/grace
rf_model_path: models/rf_model.pkl

region:
  name: "Mississippi River Basin"
  lat_min: 28.84
  lat_max: 49.74
  lon_min: -113.94
  lon_max: -77.84

# Use one of the actual GRACE files. Update this with an actual filename you see under data/raw/grace/
reference_file: data/raw/grace/20030131_20030227.tif

# Target resolution and CRS for all rasters
resolution: 0.1
bbox:
  left: -100.05
  right: -81.63
  top: 49.58
  bottom: 27.56
target_crs: EPSG:4326

# Input directories for feature datasets (match lowercased folders)
input_dirs:
  - data/raw/gldas/SoilMoi0_10cm_inst
  - data/raw/gldas/SoilMoi10_40cm_inst
  - data/raw/gldas/SoilMoi40_100cm_inst
  - data/raw/gldas/SoilMoi100_200cm_inst
  - data/raw/gldas/Evap_tavg
  - data/raw/gldas/SWE_inst
  - data/raw/chirps
  - data/raw/terraclimate/pr
  - data/raw/terraclimate/tmmn
  - data/raw/terraclimate/tmmx
  - data/raw/terraclimate/aet
  - data/raw/terraclimate/def
  - data/raw/modis_land_cover
  - data/raw/openlandmap
  - data/raw/usgs_dem

# Output file for processed feature stack
output_path: data/processed/feature_stack.nc

# ========== NEW: MODEL CONFIGURATION ==========
models:
  # Which models to train (available: rf, xgb, lgb, catb, nn, svr, gbr)
  # Based on performance results: NN (R²=0.8818), RF (R²=0.8664), XGBoost (R²=0.8182)
  enabled:
    - rf          # Neural Network (BEST: R²=0.8818, RMSE=3.7252)
    - nn          # Random Forest (2nd: R²=0.8664, RMSE=3.9609)
    - xgb         # XGBoost (3rd: R²=0.8182, RMSE=4.6200)
    #- gbr         # Gradient Boosting
    # - svr       # Support Vector Regression (slower for large data)
  
  # Model training settings
  test_size: 0.2              # Fraction of data for testing
  cross_validation: true      # Enable 5-fold cross-validation
  ensemble: true              # Create ensemble of all models
  
  # Model selection strategy
  selection_metric: "test_r2" # Metric to use for best model selection (test_r2, test_rmse, cv_r2_mean)
  
  # Optional: Custom hyperparameters (override defaults)
  hyperparameters:
    rf:
      n_estimators: 150       # Increase trees for better performance
      max_depth: 15           # Allow deeper trees
      min_samples_split: 4    # More aggressive splitting
    
    xgb:
      n_estimators: 250
      max_depth: 10
      learning_rate: 0.08
      subsample: 0.85
    
    lgb:
      n_estimators: 250
      max_depth: 10
      learning_rate: 0.08
      subsample: 0.85
    
    nn:
      hidden_layer_sizes: [512, 256, 128, 64]  # Larger network
      max_iter: 1000
      early_stopping: true
  
  # Advanced settings
  advanced:
    # Hyperparameter tuning (if you want to add this later)
    enable_tuning: false
    tuning_trials: 50
    
    # Feature selection
    feature_selection: false
    max_features: null
    
    # Model interpretability
    save_feature_importance: true
    save_predictions: true

# ========== PIPELINE SETTINGS ==========
pipeline:
  # Which model to use for groundwater calculation
  # Options: "best", "ensemble", or specific model name (rf, xgb, etc.)
  groundwater_model: "best"   # Use the best performing model
  
  # Alternative models to try if primary fails
  fallback_models: ["rf", "xgb", "ensemble"]
  
  # Skip model training if models already exist
  skip_training_if_exists: false